### PR TITLE
feat (ui): add border on req list

### PR DESCRIPTION
**Pull request by yesnault**
Explicitly add borderless class on table where we don't want border
This allow us to use standard semantics class with borders when we want

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

**Comment by yesnault** [comment]
capture d ecran 2017-12-17 a 10 40 41

**Comment by yesnault** [comment]
new screenshot with align top on all td
capture d ecran 2017-12-17 a 10 49 23

**Comment by yesnault** [comment]
it's for you @maxatome :)

**Comment by maxatome** [comment]
Nice, I am eager do try it! Thanks :)

**Comment by yesnault** [comment]
It will be in another PR

**Comment by yesnault** [comment]
here: https://github.com/ovh/cds/pull/1850

**Pull request closed without merging**
