### PR TITLE
feat(hatchery/k8s): add auth parsing to hatchery-k8s

### PR DESCRIPTION
**Pull request by yesnault**
do not squash

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-engine-cli-tools#8539.0 ✘  
* Build minimal
  * cdsctl linux ✔ 
  * check SQL Files number ✔ 
  * Engine Build linux amd64 ✘  
  * tools/debpacker ✔ 
  * tools/os-ansible-inventory ✔ 
  * Worker linux amd64 / 386 ✔

**Comment by ovh-cds** [comment]
CDS Report ut-engine#8539.0 ✘  
* Stage 1
  * Engine Test with DB ✘

**Comment by fsamin** [comment]
waiting for tests confirmation to merge

**Comment by yesnault** [comment]
tests ongoing

**Comment by yesnault** [comment]
tests ok

```
[2019-02-27T21:29:37] ✓ Le job a été mis en file d'attente
[2019-02-27T21:56:13] La Hatchery yesk8s (318) a démarré le lancement du worker avec le modèle go-1.11.2
[2019-02-27T21:56:13] La Hatchery yesk8s (318) a démarré le worker k8s-go-1-11-2-hungry-and-angry-lederberg avec succès en 0s
[2019-02-27T21:56:16] Le job 90 a été pris par le worker k8s-go-1-11-2-hungry-and-angry-lederberg
[2019-02-27T21:56:16] Worker k8s-go-1-11-2-hungry-and-angry-lederberg version:snapshot os:linux arch:amd64
[2019-02-27T21:56:16] Ce worker k8s-go-1-11-2-hungry-and-angry-lederberg a été créé pour lancer ce job
[2019-02-27T21:56:19] ✓ Le worker k8s-go-1-11-2-hungry-and-angry-lederberg a terminé et a passé 2s à travailler sur les étapes
```

**Comment by ovh-cds** [comment]
CDS Report it#8595.0 ✘  
* w-it
  * w-it ✘

**Pull request merged**
