### PR TITLE
fix (ui): no scroll on add projet page, close #609

### LINKED ISSUE #609: fix: page not scrolling on add project

### PR DESCRIPTION
**Pull request by Hugome**

### CODE REVIEW

**Comment by yesnault** [comment]
thks!

**Comment by sguiheux** [comment]
Should use <div class="scrollingContent">  below #AddProject  and maybe hide overflow-x on scrollingContent.

scrollingContent => common.scss

**Comment by Hugome** [comment]
Something like this ?
If i do a div inside the `#AddProject` with the class `scrollingContent` the padding do that :
screenshot

**Comment by sguiheux** [comment]
Overflow-x hidden ans it will be good.

**Comment by Hugome** [comment]
Its done in the code in common.scss (The screen is not the last version :))

**Pull request merged**
