### PR TITLE
chore: dep

### PR DESCRIPTION
**Pull request by yesnault**

### CODE REVIEW

**Comment by fsamin** [comment]
👍 
btw i think we should remove iffy, it was a bad idea we already have too much test dependencies

**Comment by yesnault** [comment]
@fsamin yes, totally agree. I'll test venom lib, it's more readable (proposition incoming in another PR). Removing iffy implies a tons of impacts, it will be probably in another PR for keeping this PR focusing on dep. This PR is already unreadable now :-)

**Comment by yesnault** [comment]
@fsamin for iffy, wip on https://github.com/ovh/cds/tree/ye-iffy

**Comment by fsamin** [comment]
yep for sure, no hurry to remove iffy :)
using venom lib should be great, but we have to check; i not sure i implemented the httprecorder stuff

**Pull request merged**
