### PR TITLE
plugin-kafka-publisher: Allow reading kafka password from environment…

### PR DESCRIPTION
**Pull request by byo**
… variable.

Signed-off-by: Bartłomiej Święcki <bartlomiej.swiecki@corp.ovh.com>

### CODE REVIEW

**Comment by byo** [comment]
@fsamin What's the current policy about backward-compatibility? If I convert this parameter to the named one, old usage will no longer be valid.

**Comment by fsamin** [comment]
@byo, old binaries remain functionnal; and i prefer change usage now, for the best, and support the few users of this. 
Are you agree @yesnault @sguiheux @bnjjj ?

**Comment by yesnault** [comment]
Yes, there is no good reason to put/keep password in arg. We have to remove it. A env var and (but not necessary), a user prompt should be better.

**Comment by byo** [comment]
@fsamin Did update PR, please check.

**Pull request merged**
