### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SYK-08**
Fixed 26 grammatical errors in README.md

@ovh/cds

### CODE REVIEW

**Review by yesnault — APPROVED** [review]

**Review by richardlt — APPROVED** [review]

**Comment by yesnault** [comment]
Thank you @SYK-08 

Can you sign-off your commit please (check DCO) ?

**Review by yesnault — CHANGES_REQUESTED** [review]
Thank you @SYK-08 

Can you sign-off your commit please (check DCO) ?

**Review by sguiheux — APPROVED** [review]

**Review by yesnault — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-cds#19760.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

**Comment by yesnault** [comment]
https://github.com/ovh/cds/pull/6768

**Pull request closed without merging**
