### PR TITLE
feat(cdsctl,sdk): manage vcs handlers 

### PR DESCRIPTION
**Pull request by yesnault**

### CODE REVIEW

**Comment by yesnault** [comment]
need rebase after https://github.com/ovh/cds/pull/6120 on master

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17246.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17248.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✘

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17248.1 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✘

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17250.0 ■   
* Build
  * Build and Package All ✘  
  * Build Debpacker ■   
  * Build OS-Ansible-Inventory ■   
  * Build SMTPMock ■   
  * Lint UI Translate ■   
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17250.0 ■   
* Build
  * Build and Package All ✘  
  * Build Debpacker ■   
  * Build OS-Ansible-Inventory ■   
  * Build SMTPMock ■   
  * Lint UI Translate ■   
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17251.0 ■   
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ■   
  * Build SMTPMock ■   
  * Lint UI Translate ■   
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17251.0 ■   
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ■   
  * Build SMTPMock ■   
  * Lint UI Translate ■   
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17253.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✘

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17253.1 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17253.2 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17253.2 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17257.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

**Pull request closed without merging**
