### PR TITLE
fix(hatchery:vsphere): kill awol already used provisioned workers

### PR DESCRIPTION
**Pull request by richardlt**
Signed-off-by: richardlt <richard.le.terrier@gmail.com>

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

**Review by fsamin — APPROVED** [review]

**Review by sguiheux — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#15850.1 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ■   
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ■   
  * Lint UI Translate ✔ 
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#15850.1 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ■   
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ■   
  * Lint UI Translate ✔ 
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#15850.3 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✘  
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#15850.3 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✘  
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#15850.2 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ■   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ■   
  * Test SDK Rust ✔ 
  * Test UI ✔

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#15850.3 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✘  
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ■   
  * Test SDK Rust ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#15851.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✘  
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

**Review by yesnault — APPROVED** [review]

**Pull request merged**
