### PR TITLE
feat(ui): add queue view in UI admin section

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
partially #1625
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

**Comment by yesnault** [comment]
coool !

This page should be accessible to user too, no?

admin should see everything
user should see only their jobs (as cdsctl)

**Comment by bnjjj** [comment]
@yesnault Of course but we need to find where display (in the settings menu ? or in the "admin" menu ?) and if you find a better wording too :)

**Comment by yesnault** [comment]
oh yes, it's just a wording.

admin menu -> it's for CDS Admin only (I think).  This menu should not be display to users
Settings -> Advanced? (we will confirm)

**Comment by yesnault** [comment]
So, on the navbar:
 - one icon (<i class="signal icon"></i>) on the right of icon of settings, with url: /queue
 - another icon ( <i class="heartbeat icon"></i> ) for access to status page (actually on /admin/status -> /status) 

and "status" could be removed from "admin" menu

**Comment by bnjjj** [comment]
2 more icons will be too much in the navbar. It's too ugly. At the moment I think it's better to put this link in the settings menu after the plain line separation

**Comment by yesnault** [comment]
@bnjjj less icons with that: 

capture d ecran 2018-06-03 a 11 15 29
capture d ecran 2018-06-03 a 11 26 38

Should be ok, no ? (the language switcher should be only in profile?)

**Pull request merged**
