### PR TITLE
fix(hatchery): k8s hatchery uses service account instead of kubeconfig

### PR DESCRIPTION
**Pull request by reynn**
1. Description: Helm deploy option uses a hatchery:kubernetes which requires a kubeconfig to be present. This is generally considered bad practice from what I've seen. This will convert the k8s hatchery to using an incluster config that allows it to consume a service account token. This PR also includes updates to helm charts to configure this. I've also attached a dockerfile for dev purposes that builds just the minimum required for faster local dev.
1. Related issues: #4123
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

**Comment by yesnault** [comment]
Thank you a lot! 
There is probably missing some documentation update on https://github.com/ovh/cds/blob/master/contrib/helm/cds/README.md, we'll have a look at this next week

**Comment by yesnault** [comment]
In fact, there is two things:
 - Hatchery k8s can be used by a CDS API outside k8s, so, without using helm
 - Hatchery k8s can be used by a CDS API inside k8s, with helm deploy for example

**Comment by reynn** [comment]
I reverted some of the code so that you can use a kubeconfig or service account, also updated the helm readme to remove references to copying the kubeconfig into the helm directory.

**Comment by richardlt** [comment]
Why was the ui/package.json updated in this PR ?

**Pull request merged**
