### PR TITLE
fix(api): send mail with rfc2392

### PR DESCRIPTION
**Pull request by yesnault**
Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#13078.0 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ■   
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#13078.0 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ■   
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

**Comment by yesnault** [comment]
example:

```
##### NO SMTP DISPLAY MAIL IN CONSOLE ######
Subject:[CDS] Reset your password
Text:From: no-reply@cds.local
To: <admin@localhost.local>
Subject: [CDS] Reset your password
Message-ID: <1587979061218551000.no-reply@cds.local>
```

**Comment by vbmithr** [comment]
Possible to also add a Date: field? My mail client complains…

**Pull request merged**
