### PR TITLE
feat(interpolate): add uuid support

### PR DESCRIPTION
**Pull request by ivan-velasco**
1. Description
Support to create UUID in venom api tests
1. Related issues
close https://github.com/ovh/venom/issues/748
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

**Review by richardlt — APPROVED** [review]

**Review by yesnault — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-cds#20099.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✘  
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test UI ✔

**Comment by richardlt** [comment]
PR https://github.com/ovh/cds/pull/6917 opened with the change rebased on ovh/cds:master.

**Comment by ivan-velasco** [comment]
@richardlt do you have a recommendation on how to introduce in venom sources?

**Comment by yesnault** [comment]
@ivan-velasco we'll try to remove all cds deps from venom in the next major release (with `${{…}}`). 

But, Perhaps it's possible to extend interpolate with append(interpolate.InterpolateHelperFuncs,...) directly into venom sources

**Comment by ivan-velasco** [comment]
@yesnault Forsure will give it a try.

**Pull request closed without merging**
