### PR TITLE
chore: support for go.1.11

### PR DESCRIPTION
**Pull request by yesnault**
build without vendor:
GO111MODULE=on go build

build with vendor:
GO111MODULE=on go build -mod=vendor

Signed-off-by: Yvonnick Esnault <yvonnick@esnau.lt>

### CODE REVIEW

**Comment by yesnault** [comment]
DO Not merge yet, we'll check if all builds are ok (with wm go-1.11)

**Comment by ovh-cds** [comment]
CDS Report ut-engine#5778.0 ✘  
* Stage 1
  * Engine Test with DB ✘

**Comment by ovh-cds** [comment]
CDS Report build-engine-cli-tools#5778.0 ✘  
* Build minimal
  * cds cli legacy ✔ 
  * cdsctl linux ✔ 
  * Engine Build linux amd64 ✔ 
  * tools/debpacker ✘  
  * tools/os-ansible-inventory ✔ 
  * Worker linux amd64 / 386 ✔

**Comment by ovh-cds** [comment]
CDS Report ut-engine#5779.0 ✘  
* Stage 1
  * Engine Test with DB ✘

**Comment by ovh-cds** [comment]
CDS Report build-engine-cli-tools#5818.0 ✘  
* Build minimal
  * cds cli legacy ✔ 
  * cdsctl linux ✘  
  * Engine Build linux amd64 ✘  
  * tools/debpacker ✘  
  * tools/os-ansible-inventory ✔ 
  * Worker linux amd64 / 386 ✘

**Comment by ovh-cds** [comment]
CDS Report ut-engine#5819.0 ✘  
* Stage 1
  * Engine Test with DB ✘

**Comment by ovh-cds** [comment]
CDS Report ut-engine#5820.0 ✘  
* Stage 1
  * Engine Test with DB ✘

**Comment by ovh-cds** [comment]
CDS Report build-engine-cli-tools#5820.0 ✘  
* Build minimal
  * cds cli legacy ✔ 
  * cdsctl linux ✔ 
  * Engine Build linux amd64 ✘  
  * tools/debpacker ✔ 
  * tools/os-ansible-inventory ✔ 
  * Worker linux amd64 / 386 ✔

**Comment by yesnault** [comment]
Need https://github.com/ovh/cds/pull/3297 on master before review it

**Comment by yesnault** [comment]
on it

**Comment by yesnault** [comment]
on it

**Comment by yesnault** [comment]
see https://github.com/ovh/cds/pull/3470

**Pull request closed without merging**
