### PR TITLE
feat(sdk.cdsclient): allow to pass modifiers on template apply

### PR DESCRIPTION
**Pull request by marie-j**
1. Description
Allow to pass request modifiers (query parameters) when applying a template

### CODE REVIEW

**Review by richardlt — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17737.1 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ■   
  * Build OS-Ansible-Inventory ■   
  * Build SMTPMock ■   
  * Lint UI Translate ✔ 
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17737.1 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ■   
  * Build OS-Ansible-Inventory ■   
  * Build SMTPMock ■   
  * Lint UI Translate ✔ 
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17742.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ■   
  * Build OS-Ansible-Inventory ■   
  * Build SMTPMock ■   
  * Lint UI Translate ■   
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test UI ■

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#17742.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ■   
  * Build OS-Ansible-Inventory ■   
  * Build SMTPMock ■   
  * Lint UI Translate ■   
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test UI ■

**Review by sguiheux — APPROVED** [review]

**Pull request merged**
